"""Create first migration

Revision ID: 8a6bb45c0633
Revises: 
Create Date: 2022-08-27 15:09:47.622459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6bb45c0633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.alter_column('bank_account', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'bank_account', ['id_user'])
    op.create_unique_constraint(None, 'currency', ['title'])
    op.alter_column('deposit', 'id_user',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('deposit', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('deposit', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('deposit', 'id_user',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'currency', type_='unique')
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.alter_column('bank_account', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
