"""Add email for users, and second user inthe transaction

Revision ID: ccbdeec82cec
Revises: 230e67ecbf28
Create Date: 2022-09-02 14:54:52.789171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbdeec82cec'
down_revision = '230e67ecbf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_1', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('id_user_2', sa.String(length=50), nullable=False))
        batch_op.drop_column('id_user')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('money_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('id_user_2')
        batch_op.drop_column('id_user_1')

    # ### end Alembic commands ###
